language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0snapshot

# This triggers builds to run on the new TravisCI infrastructure.
# See: http://docs.travis-ci.com/user/workers/container-based-infrastructure/
dist: xenial
sudo: false

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - vendor/bin/phpcs --standard=psr2 src/
  - vendor/bin/phpunit
